### ISSUE TITLE
Syntax highlight support

### ISSUE THREAD

**Issue by kalterberg** [hughbarney/pEmacs#3]
It would be wonderful to have pEmacs with syntax highlight support. Is someone working on it?

**Comment by hughbarney** [comment]
Thanks for your interest in pEmacs - it was one of my early experiments a while back.  I have since moved on and produced Atto and Femto - both of which support syntax highlighting but are much better code.

**Comment by hughbarney** [comment]
No longer supporting this project, there will be no further changes to it.
